Repository voxel51/fiftyone-plugins, pull requests merged in 2025-03, with the labels that each got.

#207 Prevent superfluous warnings in load_zoo_dataset operator
  plugins/zoo/__init__.py
  plugins/zoo/fiftyone.yml
Labels: bug

#221 Replace `default_visibility_labels` with `active_fields`
  plugins/utils/__init__.py
Labels: enhancement

#219 Fix null coercion bug with `manage_indexes` operator
  plugins/indexes/__init__.py
  plugins/indexes/fiftyone.yml
Labels: bug

#220 Fix missing `id` bug in `manage_delegated_operations` operator
  plugins/delegated/__init__.py
  plugins/delegated/fiftyone.yml
Labels: bug

#218 Add support for spatial indexes on visualization results
  plugins/brain/__init__.py
  plugins/brain/fiftyone.yml
Labels: feature

#223 Custom Code Preview Distribution
  plugins/scenario/__init__.py
  plugins/scenario/utils.py
Labels: feature
